/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AuthorizationRegistry__factory } from "./AuthorizationRegistry__factory";
export { DemoRelayTarget__factory } from "./DemoRelayTarget__factory";
