/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuthorizationRegistry } from "./AuthorizationRegistry";
export type { DemoRelayTarget } from "./DemoRelayTarget";
export * as factories from "./factories";
export { AuthorizationRegistry__factory } from "./factories/AuthorizationRegistry__factory";
export { DemoRelayTarget__factory } from "./factories/DemoRelayTarget__factory";
